---

rke2_data_dir: /var/lib/rancher/rke2

# This list used for Ha Proxy configuration 
rke2_ha_list: 
- master01 10.201.4.1
- master02 10.201.4.2
- master03 10.201.4.3

# Kubernetes API and RKE2 registration IP address. The default Address is the IPv4 of the Server/Master node.
# In HA mode choose a static IP which will be set as VIP in keepalived.
# Or if the keepalived is disabled, use IP address of your LB.
rke2_api_ip: "10.201.4.1" #HA VIP IP

# Add additional SANs in k8s API and Ha Proxy TLS cert
rke2_additional_sans: 
- 10.201.4.1
- 10.201.4.2
- 10.201.4.3

# Pre-shared secret token that other server or agent nodes will register with when connecting to the cluster
rke2_token: L6vaWjzPq8NkYcTQRXm3bGW1Av9ZJXU2dH7eBYgKCfsEpMtAW5nhry6mDLqVoTx

# RKE2 version [v1.31.1+rke2r1]
rke2_version: v1.31.1+rke2r1

# Deploy RKE2 and set the custom containerd images registries [active or disabled]
custom_registry: deactive

# Mirror for Insecure Registries [active or disabled]
custom_mirror: deactive

# Registry Address, User and Password for using Private Registries without secret configuration
registry_address: 
  - registry.com
registry_user: admin
registry_password: admin123

# Default Ansible Inventory Group name for RKE2 cluster
rke2_cluster_group_name: nextprod_rke2_k8s_cluster

# Default Ansible Inventory Group name for RKE2 Servers
rke2_servers_group_name: masters

# Default Ansible Inventory Group name for RKE2 Agents
rke2_agents_group_name: workers